### ISSUE TITLE
Validation avec MailChimp

### ISSUE THREAD

**Issue by AlphonseJr** [MathieuNls/tw#184]
Pour améliorer la dévilérabilité de nos mails MailChimp, on aurait besoin de faire la manip suivante :

Je vous invite à vous connecter sur votre compte chez Cloudflare ajouter l'entrée CNAME ci dessous à la zone DNS.
k1._domainkey.toolwatch.io 0 CNAME dkim.mcsv.net.

Mentionnez comme sous domaine k1._domainkey et comme cible dkim.mcsv.net. (veuillez ne pas oublier le "." après .net ).

Thanks Hook :)

**Comment by MathieuNls** [comment]
Je peux avoir l'original de ce post / message ? Le format du CNAME est invalide.

**Comment by AlphonseJr** [comment]
Ca te va ça ? 

![image](https://cloud.githubusercontent.com/assets/6577742/19316945/a3394dd2-90a3-11e6-849e-f764dbf65408.png)

**Comment by MathieuNls** [comment]
Done
